spring:
    datasource:
        driverClassName: org.h2.Driver
        password: password
        url: jdbc:h2:mem:costco
        username: sa
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
    h2:
        console:
            enabled: true
application-description: A customer receives 2 points for every dollar spent over $100 in each transaction, plus 1 point for every dollar spent over $50 in each transaction(e.g. a $120 purchase = 2x$20 + 1x$50 = 90 points).
application-version: 1.0
logging:
    file:
        name: code-challenge-logs.txt
        path: /path/to/a/file